### ISSUE TITLE
和daycount放进mcdr的插件文件夹，.json改过了，重加载插件，重进服没有提示

### ISSUE THREAD

**Issue by TANGhz17** [TISUnion/joinMOTD#1]
拜佛.jpg
原版+地毯服（这个没影响吧，我感觉
是不是还有什么没有改

**Comment by TANGhz17** [comment]
[MCDR] [23:05:05] [MainThread/INFO]: Loading plugins
[MCDR] [23:05:05] [MainThread/INFO]: Plugin ./plugins/Calculator.py reloaded
[MCDR] [23:05:05] [MainThread/INFO]: Plugin ./plugins/daycount.py reloaded
[MCDR] [23:05:05] [MainThread/WARNING]: Fail to load plugin ./plugins/joinMOTD.py
[MCDR] [23:05:05] [MainThread/WARNING]: Traceback (most recent call last):
  File "C:\Users\MinecraftServer\SuperXK\Survival\utils\plugin_manager.py", line 20, in load_plugin
    plugin.load()
  File "C:\Users\MinecraftServer\SuperXK\Survival\utils\plugin.py", line 30, in load
    self.module = tool.load_source(self.file_name)
  File "C:\Users\MinecraftServer\SuperXK\Survival\utils\tool.py", line 24, in load_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./plugins/joinMOTD.py", line 4, in <module>
    from daycount import getday
ModuleNotFoundError: No module named 'daycount'

**Comment by Fallen-Breath** [comment]
需要daycount这个插件

**Comment by TANGhz17** [comment]
[Server] [09:00:01] [Server thread/INFO]: TANGhz17 joined the game
Exception in thread on_player_joined@joinMOTD:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./plugins/joinMOTD.py", line 53, in on_player_joined
    onPlayerJoin(server, playername)
  File "./plugins/joinMOTD.py", line 23, in onPlayerJoin
    with open(ConfigFilePath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/joinMOTD.json'
![QQ图片20200407090329](https://user-images.githubusercontent.com/42084546/78619033-b97f6d00-78ae-11ea-9583-777d51f751b6.png)
![QQ图片20200407090334](https://user-images.githubusercontent.com/42084546/78619036-bab09a00-78ae-11ea-941c-7c68bc83f573.png)

**Comment by TANGhz17** [comment]
找不到json可它就在这个目录里啊
@Fallen-Breath 
有点看不懂

**Comment by Fallen-Breath** [comment]
在修了修好了现在可以跑了

**Comment by TANGhz17** [comment]
Exception in thread on_player_joined@joinMOTD:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./plugins/joinMOTD.py", line 58, in on_player_joined
    onPlayerJoin(server, playername)
  File "./plugins/joinMOTD.py", line 26, in onPlayerJoin
    with open(ConfigFilePath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/joinMOTD.json'
我。。。。。
更新一下之后，

**Comment by Fallen-Breath** [comment]
要写配置文件呀

**Comment by TANGhz17** [comment]
耶，修好了，配置文件应该放在MCDR\config\joinMOTD.json，怪不得老是告诉我找不到文件，我原来放在joinMOTD.py同层了 <3
再次拜佛

**Comment by 4O4NtFd** [comment]
同求，我的joinMOTD也是一直不好使
![QQ截图20200701211854](https://user-images.githubusercontent.com/49442853/86250135-c926fd00-bbe2-11ea-8a02-1e3fb284e755.png)
![QQ截图20200701213310](https://user-images.githubusercontent.com/49442853/86250149-ccba8400-bbe2-11ea-98af-71ac519b464b.png)
